name: Craigwfox.com
highlighter: rouge
permalink: pretty

exclude: [
	node_modules,
	src,
	"*.sublime-project",
	"*.sublime-workspace",
	"Gruntfile.js",
	"gulpfile.js",
	"CNAME",
	"LICENSE",
	"npm-debug.log",
	"package.json",
	"README.md"
]
